variables:
  CLUSTER_NAME: iowa-a
  CONFIG_REPO: git@github.com:mozmeao/www-config
  CONFIG_BRANCH: master

stages:
  - build
  - update-config
  - deploy

build:
  stage: build
  only:
    - master
    - stage
    - prod
  tags:
    - oregon-b-shell
  script:
    - make clean build-ci
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock_test docker/bin/push2dockerhub.sh
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock_assets docker/bin/push2dockerhub.sh
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock_code docker/bin/push2dockerhub.sh
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock_build docker/bin/push2dockerhub.sh
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock docker/bin/push2dockerhub.sh
    - bin/upload-staticfiles.sh

build-test:
  stage: build
  only:
    - run-integration-tests
  tags:
    - oregon-b-shell
  script:
    - make clean build-ci
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock_test docker/bin/push2dockerhub.sh
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock docker/bin/push2dockerhub.sh

include:
  - remote: https://raw.githubusercontent.com/mozmeao/gitlab-library/master/ingress.yml

build-demo-ingress:
  extends: .combined-ingress
  stage: deploy
  only:
    - "/demo/.*/"
  variables:
    port: 80
    service: bedrock
    domain: mozmar.org
    staging: ''
    dns_prefix: '--service_prefix www'

build-demo-deploy:
  extends: .base_job
  stage: deploy
  only:
    - "/demo/.*/"
  variables:
    secret_namespace: demo-shared-bedrock
  environment:
    on_stop: stop-demo-app
    name: www-$CI_COMMIT_REF_NAME
  script:
    - export KUBECONFIG=$EUKUBECONFIG
    - echo $CI_COMMIT_REF_SLUG
    - make clean build-demo-ci
    - FROM_DOCKER_REPOSITORY=mozorg/bedrock_demo docker/bin/push2dockerhub.sh
    - kubectl create namespace $CI_COMMIT_REF_SLUG || true
    - kubectl get secret bedrock-secrets --namespace=secret_namespace --export -o yaml | kubectl apply --namespace=$CI_COMMIT_REF_SLUG -f -
    - helm repo add mozmeao https://mozmeao.github.io/helm/
    - helm repo update
    - helm install bedrock mozmeao/bedrock --namespace $CI_COMMIT_REF_SLUG --set shared.image.version=$CI_COMMIT_SHA --set shared.image.dockerrepo=mozorg/bedrock_demo || true
    - helm upgrade bedrock mozmeao/bedrock --namespace $CI_COMMIT_REF_SLUG --set shared.image.version=$CI_COMMIT_SHA --set shared.image.dockerrepo=mozorg/bedrock_demo || true

stop-demo-app:
  stage: deploy
  tags:
    - oregon-b-shell
  variables:
    GIT_STRATEGY: none
  environment:
    action: stop
    name: www-$CI_COMMIT_REF_NAME
  when: manual
  script:
    - export KUBECONFIG=$EUKUBECONFIG
    - kubectl delete ns/$CI_COMMIT_REF_SLUG


.update-config:
  stage: update-config
  tags:
    - oregon-b-shell
  script:
    - bin/update_config.sh

dev:
  extends: .update-config
  only:
    - master
  variables:
    NAMESPACE: bedrock-dev

stage:
  extends: .update-config
  only:
    - stage
  variables:
    CLUSTERS: iowa-a
    NAMESPACE: bedrock-stage

test:
  extends: .update-config
  only:
    - run-integration-tests
  variables:
    CLUSTERS: oregon-b
    NAMESPACE: bedrock-test

prod:
  extends: .update-config
  only:
    - prod
  variables:
    CLUSTERS: frankfurt iowa-a
    NAMESPACE: bedrock-prod
